name: .NET Desktop

on:
  push:
    branches:
      - main  # Cambia esto a la rama que desees desplegar
  pull_request:
    branches:
      - main  # Cambia esto a la rama que desees desplegar

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Asegúrate de que coincida con tu versión de .NET

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MyMvcApp-Contact-Database-Application'  # Reemplaza con el nombre de tu Aplicación Web
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/publish
